### ISSUE TITLE
学バスの時刻表データ (JSON) について

### ISSUE THREAD

**Issue by Meiryo7743** [newt239/sit-bus#1]
同じ大学の者です。先日たまたま <https://sit-bus.vercel.app> の存在を知り，こちらのレポジトリを拝見しています

[`functions.ts`](https://github.com/newt239/sit-bus/blob/main/src/utils/functions.ts) のところで `bus_data.json` を取得し，~~あのヒドいデータ構造と格闘しながら~~頑張って処理している様子が伺えました

もし良ければ，自分が昔作ったツール (<https://github.com/Meiryo7743/sbdcg>) が少しでも役立てば良いな……と思い，この issue を立てた次第です。また，場合によってはツールを改良し，こちらのサイトで取り扱いやすい学バスの時刻表データを提供できればとも考えています。いかがでしょうか……？

**Comment by newt239** [comment]
本アプリケーションに関心をお寄せいただきありがとうございます。
ご提案いただいた件ですが、@Meiryo7743 さんのCSVファイルを利用するにあたって定期的なバッチ処理が必要となることや、今後機能拡張を検討する際に生データを参照した方が変更を加えやすいこと等を踏まえ、本プロジェクトではこれまで通り独自のパース処理を採用することとしました。
わざわざご提案いただいたところ大変心苦しいのですが、ご理解いただけますと幸いです。
